static:
	bash ./build.sh static $(_PATH_ROOT)

dynamic:
	bash ./build.sh dynamic $(_PATH_ROOT)

install:
	bash ./install.sh "" $(_PATH_ROOT)

force:
	bash ./install.sh force $(_PATH_ROOT)

uninstall:
	bash ./uninstall.sh "" $(_PATH_ROOT)