static: 
	make static _PATH_ROOT=$(_PATH_ROOT) -C cfg
	make static _PATH_ROOT=$(_PATH_ROOT) -C ini
	make static _PATH_ROOT=$(_PATH_ROOT) -C opt
	make static _PATH_ROOT=$(_PATH_ROOT) -C script

dynamic:
	make dynamic _PATH_ROOT=$(_PATH_ROOT) -C cfg
	make dynamic _PATH_ROOT=$(_PATH_ROOT) -C ini
	make dynamic _PATH_ROOT=$(_PATH_ROOT) -C opt
	make dynamic _PATH_ROOT=$(_PATH_ROOT) -C script

clean: 
	make clean _PATH_ROOT=$(_PATH_ROOT) -C cfg
	make clean _PATH_ROOT=$(_PATH_ROOT) -C ini
	make clean _PATH_ROOT=$(_PATH_ROOT) -C opt
	make clean _PATH_ROOT=$(_PATH_ROOT) -C script
	
